BEGIN;

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery as ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

DROP TABLE IF EXISTS shopping_list;
CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY default AS IDENTITY,
  name TEXT NOT NULL,
  price decimal(10, 2) NOT NULL,
  date_added TIMESTAMP default now() NOT NULL,
  checked BOOLEAN default false NOT NULL,
  category grocery NOT NULL
);

COMMIT;
